r4813 bugfix: when long action takes place, RackTables allows user to work simultaneously in different tabs
init.php: unconditional session_start was removed
buildRedirectURL: the function was moved to functions.php and merged with redirectUser.
updVSTRule: added session_start in order to use PHP sessions engine
renderVSTRulesEditor: idem
getCellFilter: idem
showMessageOrError: display merged list of messaged (from session and from log_messages array)
redirectIfNecessary: remember last tab code moved here from index.php
redirectUser: func prototype changed, also backs up global $log_messages into _SESSION.
showOneLiner: use global $log_messages instead of _SESSION.
getMessagesCount: idem