justify IAE -> IRAE conversion
InvalidArgException: remove 3 accessor methods to stop exposing
  unnecessary details, add two class conversion methods
convertToIRAE(): reduce and deprecate
assertDateArg(): switch to InvalidArgException::newIRAE()
assertIPArg(): idem
assertIPv4Arg(): idem
assertIPv6Arg(): idem