r4497 bugfix: LiveVlans was not displaying messages properly
setSwitchVLANs: removed support of returning message codes from gateway, added support for returning plain text messages of any kind
showMessageOrError: removed unused message codes

switchvlans/main: replaced integer-encoded messages by plain text ones
switchvlans/cisco.connector: idem