802.1q locks refactoring
This change addresses some issues the with 802.1Q deploy process.
First, InnoDB deadlocks happen from time to time. I don't actually
deeply understand the root cause of this, but believe it should be
fixed if a DB transaction would not wait for device communication to
complete.
Second, it is possible that a device being updated its 802.1Q desired
config while the deploy is performed in background, ends up in changed
(D != C), but synchronized state (out_of_sync = no).

The idea of this change is to clarify the lock logic using new API
to modify the VLANSwitch state, and to make DB transactions shorter.

VLANSwitch state API consists of:

touchVLANSwitch: no changes, just return modified rows count
detouchVLANSwitch: the opposite function, sets oos to 'no'
	only if mutex_rev is equal to the given previous value
setVLANSwitchError: modifies just the last_errno, last_error_ts values
setVLANSwitchTimestamp: modifies any timestamp field in VLANSwitch

Other functions changed:

exportSwitch8021QConfig: sets last_push_started, last_push_finished DB fields
exec8021QDeploy:
- sets DB mutex to disallow simultaneous deploy on the same object.
- begin transaction only after running config is retrieved, commit it
  before the push process begins.
- use new detouchVLANSwitch to ensure out_of_sync won't be set no 'no'
  after mutex_rev is increased by someone else.