r4750 ability to remove 802.1q VLAN from every port it belongs to in order to delete this VLAN
save8021QPorts: made using new apply8021qChangeRequest function
clearVlan: new ophandler
deleteVlan: new ophandler
showMessageOrError: removed unused message code (41)
renderEditVlan: new Edit tab on vlan page handler
touchVLANSwitch: new DB function making the switch out_of_sync
exec8021QDeploy : made using of new touchVLANSwitch
queueChangesToSwitch: idem
saveDownlinksReverb: idem, now returns ports count
initiateUplinksReverb: now returns ports count
apply8021qChangeRequest: new function for saving D-config