r4487 The error messaging system is renewed, legacy stuff is removed
buildRedirectURL: it is renamed buildWideRedirectURL, now is has nothing to do with logs, only URLs, which makes sence
Old buildRedirectURL is removed, use showFuncMessage instead. It has nothing to do with URLs, only logs

Replaced call to buildRedirectURL by showFuncMessage in most ophandlers, cause the only sence of calling it was to show message
editAddress: checking the retval of DB function removed
editv6Address: idem

processGridForm: now returns BOOL instad of log array
updateObjectAllocation: reflecting changes in processGridForm
updateRackDesign: idem
updateRackProblems: idem

setSwitchVLANs: now sets log messages by itelf, returns nothing
setPortVLAN: reflecting changes in setSwitchVLANs

showMessageOrError: removed unused msgcodes and the spport of old v1 and v2 log formats

emptyLog: not needed any more, removed
oneLiner: idem
mergeLogs: idem

setMessage: reflecing v3 version of log
getMessagesCount: idem
showOneLiner: new function constructing and queueing v3 log message by its code
showFuncMessage: same but with search in $msgcode. Used everywhere instead of former buildRedirectURL