r4435 new feature: port change history
getPortInfo and getObjectPortsAndLinks changed their result arrays schemas.
Now they are equal, and includes last log message, log count, port link data, remote and local object names.

unlinkPort: new ophandler needed instead of tableHandler
linkPortForObject: removed unnesessary getPortInfo and spotEntity calls
showMessageOrError: log message on port linked was changed

renderRackObject: removed unnessesary spotEntity, added log item formatting
renderPortsForObject: idem
renderObject8021QPorts: idem
renderDiscoveredNeighbors: removed unnessesary spotEntity

fetchPortList: new function to fetch unified port data from DB
getPortInfo: changed the result schema, it is extended. Now it is a dummy function using fetchPortList
getObjectPortsAndLinks: idem
getPortReservationComment: new function to fetch port reservation comment only
commitUpdatePort: puts the change message into PortLog
commitUpdatePortComment: idem
linkPorts: idem
commitUnlinkPort: new function for unlinking doing logging of this op
addPortLogEntry: new function to store port log message

formatLinkedPort: new function to format the HTML-link to remote port linked with the specified port.
formatLoggedSpan: new function to format HTML-text with the on-hover log message
formatPortReservation: added log item formatting
formatAge: time duration 'humanizer'

dispatchAJAXRequest: added second getPortInfo call to fetch newly created log message