r3860 Another round of exceptions cleanup. 1. Make sure, that objects thrown by RackTables code always belong    to RackTablesError or its sub-class. 2. Explicitly tell the classes, which make difference upon catching.
ajax.php: return a short text in case of error, not an HTML page
render_image.php: return error image in case of error

index.php: make use of RackTablesError class
process.php: idem
init.php: idem
addFileToEntity(): idem
linkFileToEntity(): idem
renderSearchResults(): idem
add8021QPort(): idem
del8021QPort(): idem
upd8021QPort(): idem
loadConfigDefaults(): idem
isConfigVarChanged(): idem
getConfigVar(): idem
iptree_embed(): idem
processAdjustmentSentence(): idem
setConfigVar(): idem, and indicate unwanted changes with InvalidRequestArgException
setUserConfigVar(): idem, and idem
resetUserConfigVar(): idem, and idem

updateUI(): drop catch block and let upper level handle failure
saveMyPreferences(): idem
resetMyPreference(): idem

submitSLBConfig(): narrow down more specific handling to RTGatewayError case
renderDiscoveredNeighbors(): idem
exec8021QDeploy(): idem

InvalidArgException: make a subclass of RackTablesError
RTGatewayError: new class instead of E_GW_FAILURE

queryGateway(): make use of RTGatewayError
getSwitchVLANs(): idem
gwSendFile(): idem
gwSendFileToObject(): idem
getRunning8021QConfig(): idem
setDevice8021QConfig(): idem
gwRetrieveDeviceConfig(): idem
gwDeployDeviceConfig(): idem
xos12Read8021QConfig(): idem